{% set name = "dialog" %}
{% set version = "1.3_20251001" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://invisible-mirror.net/archives/{{ name }}/{{ name }}-{{ version | replace("_", "-") }}.tgz
  sha256: bee47347a983312facc4dbcccd7fcc86608d684e1f119d9049c4692213db96c3

build:
  number: 0
  skip: true  # [win]
  script: |
    ./configure \
      --prefix="$PREFIX" \
      --enable-nls \
      --with-shared \
      --with-shlib-version=abi \
      --with-ncursesw \
      --disable-rpath-hack
    make -j "${CPU_COUNT:-1}"
    make install-full
    rm -f "$PREFIX/lib/libdialog.a"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - pkg-config
  host:
    - ncurses

test:
  commands:
    - dialog --print-text-only "Hello World!"

about:
  home: https://invisible-island.net/dialog/
  summary: 'A tool to display dialog boxes from shell scripts'
  description: |
    Dialog is a program that will let you present a variety of questions or
    display messages using dialog boxes from a shell script.
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - op3
